# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.CharField(blank=True, max_length=255, null=True)),
                ('permalink', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('formatted_date', models.CharField(blank=True, max_length=255, null=True)),
                ('retweets', models.CharField(blank=True, max_length=255, null=True)),
                ('favorites', models.CharField(blank=True, max_length=255, null=True)),
                ('mentions', models.CharField(blank=True, max_length=255, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
                ('geo', models.CharField(blank=True, max_length=255, null=True)),
                ('urls', models.CharField(blank=True, max_length=255, null=True)),
                ('author_id', models.CharField(blank=True, max_length=255, null=True)),
                ('busqueda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PTGRIS.Busqueda')),
            ],
        ),
    ]
