# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTGRIS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busqueda',
            name='id',
        ),
        migrations.AddField(
            model_name='busqueda',
            name='folio',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
